name: Build Artifacts

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_linux_x86_64:
    name: Build on GNU/Linux x86_64 (Bare metal worker)
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Enable cargo caching
        uses: Swatinem/rust-cache@v2

      - name: Build and Test release binary
        run: |
          cargo build --release -F qemu

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        with:
          name: scaphandre
          path: target/release/scaphandre
