name: Build Artifacts

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_linux_x86_64:
    name: Build on GNU/Linux x86_64 (Bare metal worker)
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Enable cargo caching
        uses: Swatinem/rust-cache@v2

      - name: Build and Test release binary
        run: |
          cargo build --release -F qemu

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        with:
          name: scaphandre
          path: target/release/scaphandre

      - name: Upload release artifact
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # fixed to kraut
          upload_url: https://uploads.github.com/repos/maxhoesel/scaphandre/releases/200117323/assets{?name,label}
          asset_path: target/release/scaphandre
          asset_name: scaphandre
          asset_content_type: application/octet-stream
